######################################################################
# Automatically generated by qmake (3.0) ?? 1? 5 15:13:10 2017
######################################################################

TEMPLATE = app
TARGET = BridgeServer
INCLUDEPATH += .

# Input
HEADERS += BridgeServer/BridgeServer.h BridgeServer/BridgeServerDialog.h
SOURCES += BridgeServer/BridgeServer.cpp \
           BridgeServer/BridgeServerDialog.cpp \
           BridgeServer/main.cpp
QT += widgets network
